name: Build IPK

on:
  push:
  workflow_dispatch:

env:
  PACKAGE_NAME: luci-app-watchdog

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare SDK
      run: |
        git clone --depth 1 https://github.com/linkease/openwrt-app-actions.git sdk
        cd sdk
        chmod +x sdk.sh
        ./sdk.sh init

    - name: Add package
      run: |
        rm -rf sdk/package/${PACKAGE_NAME}
        mkdir -p sdk/package/${PACKAGE_NAME}
        cp -r . sdk/package/${PACKAGE_NAME}/

    - name: Build package
      run: |
        cd sdk
        chmod +x sdk.sh
        ./sdk.sh build ${PACKAGE_NAME}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ipk
        path: sdk/bin/packages/**/*.ipk
